name: CI iOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Force Xcode 15
      run: sudo xcode-select -switch /Applications/Xcode_15.0.app
    - name: Run tests
      run: xcodebuild clean test -project "Connected.xcodeproj" -scheme "Connected" -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=latest"
    - name: Build App
      run: xcodebuild -project "Connected.xcodeproj" -scheme "Connected" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
