name: CI-iOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
 build-and-test:
  runs-on: macos-13

  timeout-minutes: 5

  steps:
  - uses: actions/checkout@v2
  
  - name: Select Xcode
    run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app
  - name: Build & Test
    run: xcodebuild clean build test -workspace Connected.xcworkspace -scheme Connected CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=17.0'
   
