name: CI-iOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
 build-and-test:
  runs-on: macos-13

  timeout-minutes: 10

  steps:
  - uses: actions/checkout@v2
  
  - name: Select Xcode
    run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app
  - name: Build & Test
    run: xcodebuild test -workspace Connected/Connected.xcworkspace -scheme "Connected" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0.1" ONLY_ACTIVE_ARCH=YES SWIFT_TREAT_WARNINGS_AS_ERRORS=YES OTHER_SWIFT_FLAGS="-D ED_SKIP_SWIFT_FORMAT"
   
